language: clojure
lein: lein2
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - sudo add-apt-repository ppa:shnatsel/dnscrypt -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libsodium
