language: clojure
lein: lein2
jdk:
  - oraclejdk7
  - oraclejdk8
install:
  - sudo apt-get -qq update
  - sudo apt-get -y -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  - wget https://b25518159d104e8997f8-d5f47ab458856b6ee0c2780ddf5e291c.ssl.cf5.rackcdn.com/libsodium-1.0.0_amd64.deb
  - sudo dpkg -i libsodium-1.0.0_amd64.deb
